-- MySQL Script generated by MySQL Workbench
-- Wed Oct 29 12:53:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sol_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sol_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sol_db` DEFAULT CHARACTER SET utf8 ;
USE `sol_db` ;

-- -----------------------------------------------------
-- Table `sol_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sol_db`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `paternal_surname` VARCHAR(100) NOT NULL,
  `maternal_surname` VARCHAR(100) NOT NULL,
  `phone_number` BIGINT NOT NULL,
  `photo_dir` VARCHAR(256) NOT NULL,
  `can_operate` TINYINT NOT NULL DEFAULT 0,
  `session_token` VARCHAR(20) NULL DEFAULT NULL,
  `session_expires` DATETIME NULL DEFAULT NULL,
  UNIQUE INDEX `usuarios_1` (`email` ASC) VISIBLE,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sol_db`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sol_db`.`stock` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `description` TEXT NOT NULL,
  `price` FLOAT NOT NULL,
  `available` INT NOT NULL,
  `photo_dir` VARCHAR(256) NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_usuario_stock1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_stock1`
    FOREIGN KEY (`user_id`)
    REFERENCES `sol_db`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sol_db`.`guest_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sol_db`.`guest_token` (
  `token_id` INT NOT NULL,
  `token` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`token_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sol_db`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sol_db`.`ticket` (
  `product_id` INT NOT NULL,
  `ticket_id` INT NOT NULL,
  `token_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `requester_name` VARCHAR(120) NOT NULL,
  `phone_number` BIGINT NOT NULL,
  `directions` TEXT NULL,
  PRIMARY KEY (`product_id`, `ticket_id`, `token_id`),
  INDEX `fk_compra_token1_idx` (`token_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_stock1`
    FOREIGN KEY (`product_id`)
    REFERENCES `sol_db`.`stock` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_token1`
    FOREIGN KEY (`token_id`)
    REFERENCES `sol_db`.`guest_token` (`token_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
